name: yamela

on: 
  push

jobs:
  build-job:
    steps:
      - uses: edders/test-pipeline/.github/workflows/main.yml@9cf8d0a0a134fd28eaed6fb82bbafbe70b1ebcf3
      - name: build
      - echo "Hello, $GITLAB_USER_LOGIN! Get fucked"

  test-job1:
    steps:
      - uses: edders/test-pipeline/.github/workflows/main.yml@9cf8d0a0a134fd28eaed6fb82bbafbe70b1ebcf3
      - name: test
      - echo "This job tests something"

  test-job2:
    steps:
      - uses: edders/test-pipeline/.github/workflows/main.yml@9cf8d0a0a134fd28eaed6fb82bbafbe70b1ebcf3
      - name: test
      - echo "This job tests something, but takes more time than test-job1."
      - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
      - echo "which simulates a test that runs 20 seconds longer than test-job1"
      - sleep 20

  deploy-prod:
    steps:
      - uses: edders/test-pipeline/.github/workflows/main.yml@9cf8d0a0a134fd28eaed6fb82bbafbe70b1ebcf3
      - name: deploy
      - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."